# Generated by Django 5.0 on 2023-08-03 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0056_remove_poojaorder_quantity_poojaorder_bookeddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pooja",
            name="dateofpuja",
            field=models.CharField(
                default=datetime.datetime(2023, 8, 4, 8, 21, 18, 271575),
                max_length=12,
                null=True,
            ),
        ),
    ]
