# Generated by Django 5.0 on 2023-08-03 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0057_alter_pooja_dateofpuja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pooja",
            name="dateofpuja",
            field=models.CharField(
                default=datetime.datetime(2023, 8, 4, 8, 43, 44, 985371),
                max_length=12,
                null=True,
            ),
        ),
    ]
