# Generated by Django 4.2.10 on 2024-02-26 05:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0061_answerfaqtime_exp_answerfaqtime_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="Pooja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pooja_faq",
                to="adminapp.pooja",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapp.products",
            ),
        ),
    ]
