# Generated by Django 4.2.10 on 2024-02-26 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0062_answerfaqtime_exp_answerfaqtime_icon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faq",
            old_name="Pooja",
            new_name="pooja",
        ),
    ]
