# Generated by Django 4.2.10 on 2024-02-26 07:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0063_rename_pooja_faq_pooja_answerfaqtime_exp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="squ_type",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("squ_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminapp.categoryofproduct",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="products",
            name="squ",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="adminapp.sku",
            ),
        ),
    ]
