# Generated by Django 4.2.10 on 2024-02-26 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0064_answerfaqtime_exp_answerfaqtime_icon_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="squ",
            new_name="sku",
        ),
        migrations.RenameField(
            model_name="products",
            old_name="squ_type",
            new_name="sku_type",
        ),
        migrations.RenameField(
            model_name="sku",
            old_name="squ_name",
            new_name="sku_name",
        ),
    ]
