from django.urls import path
from . import views


urlpatterns = [
    path('register/', views.UserRegister),
    path('', views.HomePage),
    path('puja/', views.OurServices),
    path('servicefilter/<int:id>/', views.FilterByCategory, name="puja"),
    path('pujadetail/<int:id>/', views.ViewPujaDetail, name='pujadetail'),    
    path('pujaslot/<int:id>/', views.AddPoojaSlot, name="pujaslot"),
    path('viewpujadiscrip/<int:id>/', views.ViewPujadescription, name="viewpuja"),
    path('products/', views.OurProducts),
    path('productfilter/<int:id>/', views.FilterProductByCategory, name="prod"),
    path('horoscope/<int:id>/', views.FilterHoroscopeByCategory, name='horoscope'),
    path('proddetail/<int:id>/', views.ViewProductDetail, name='proddetail'),
    path('addtocart/<int:id>/', views.AddToCart, name="addcart"),
    path('showcart/', views.ViewCartProduct, name="payid"),
    path('viewproddiscrip/<int:id>/', views.ViewProductdescription, name="viewprod"),
    path('checkout/', views.Checkout),
    path('service/ask-a-question/', views.QusAndAnswerView),
    path('service/ask-a-question/checkout/', views.QusAndAnswerViewPayment),
    path('profile/', views.ShowProfileDetail),
    path('editprofile/<int:id>/', views.EditProfileView, name='editpro'),
    path('pujaslot/', views.ViewPujaSlotBooking),
    path('blogs/', views.DailyBlosView),
    path('family-friend-create/', views.FamilyFriendCreate),
    path('view-family-friend/', views.AddFriendView),
    path('edit-friend-profile/<int:id>/', views.EditFriendProfileView, name='editfamilypro'),    
    path('delete-friend-profile/<int:id>/', views.DeleteFriendProfile, name='delfamilypro'),
    path('order-history/', views.GetOrderView),
    path('customer-support/', views.SendCustomerSupport),
    # path('horoscope/', views.HoroscopeView),
    path('service/questions/reply/', views.ShowFAQReply),
    path('product/order/history/', views.ShowOrderlist),
    path('puja/order/history/', views.ShowPojaSlot),
    path('service/ask-a-question/payment/history/', views.ShowFaqPayment),
    path('delete-item/<int:id>/', views.DeleteCart, name='delcart'),
    path('delete-puja-slot/<int:id>/', views.DeletePoja, name='delpuja'),
    path('delivery-address/', views.OrderPlaceAddres),
    path('add-to-wallet/', views.AddWalletAmount, name="wallet"),
    path('confirm-payment/',views.PaymentByRazorpay),
    path('pay-with-wallet/',views.PayWithWallet),
    path('puja/pay-with-wallet/',views.PayWithWalletforPuja),
    path('service/questions/pay-with-wallet/',views.PayWithWalletforQA),
    path('service/questions/checkout/',views.CheckoutforQA),
    path('puja/checkout/',views.CheckoutforPuja),
    path('forgot-password/',views.SendMailToPassword,name='mailpass'),
    path('changeuserpassword/<int:id>/<str:username>/',views.UserForgotPassword, name='changepass1'),
    
    #path('termsofuse/',views.Termsofuse),
    path('terms-and-condition/',views.TermsandCondition),
    path('privacy-policy/',views.PrivacyPolicy),
    path('contact/',views.Contact),
    path('shipping-policy/',views.ShippingPolicy),    
    path('refund-policy/',views.RefundPolicy),
    
]